[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build]
  command = "astro build"

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"

[[headers]]
  for = "/_astro/*"
    [headers.values]
      Cache-Control = "public, max-age=604800, immutable"